name: Add comment with useful URLs to pull request
on: pull_request

jobs:
  add-comment:
    name: Add Links to PR
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: actions/github-script@0.5.0
        with:
          script: |
            const branch = context.payload.pull_request.head.ref

            const pattern = /^ope-\d+(-|$)/i
            if (!pattern.test(branch)) {
                console.log(`Ignoring PR for branch ${branch} as it does not fit branch name pattern`)
                return
            }

            const prefix = branch.split('-', 2).join('-')
            const nodeploy = branch.endsWith('-nodeploy')

            const urls = {}

            urls.JIRA = `https://app.camunda.com/jira/browse/${prefix.toUpperCase()}`
            urls.Stage = nodeploy ? 'not deployed' : `https://${prefix.toLowerCase()}.operate.camunda.cloud`
            urls.Jenkins = `https://ci.operate.camunda.cloud/job/camunda-operate/job/${branch}`

            const body = Object.entries(urls).map(e => `|${e[0]}|${e[1]}|`).join('\n')

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `|Link|URL|\n|----|----|\n${body}`
            })
