name: Add comment with stage URL to pull request
on: pull_request
jobs:
  add-comment:
    name: Add comment to issue
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)
            const issueId = context.head_ref.split('-', 2).join('-')
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Staging enviroment will be availabe at htts://${issueId}.operate.camunda.cloud`
            })
