name: Add comment with stage URL to pull request
on: pull_request
jobs:
  add-comment:
    name: Add comment to issue
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Check out this message!"
